- name: loops packages
  hosts: frontend
  become: yes
  tasks:
  - name: loops installing packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql