- name: nginx install and start
  hosts: fronend
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present
      msg: "installing nginx"

  - name: start nginx
    ansible.builtin.service:
    name: nginx
    state: started
    msg: "running the nginx"